maximum_name: 50
maximum_email: 100
minimum_password: 6
maximum_word: 50
maximum_meaning: 100
maximum_name_category: 50
maximum_ans: 4
maximum_words_in_lesson: 20
increase_index: 1
right_answer: 1
check_lesson: 1
users_per_page: 10
words_per_page: 10
paragraph: "20 words of caterory: "
all_words: "all_words"
